### PR TITLE
Updated launch.sh with Discord integration

### PR DESCRIPTION
**Pull request by ArrowPrint**
Here’s the updated brief description of all the changes made to the launch.sh file:

Discord Integration: Added functionality to send welcome and goodbye messages to a Discord webhook for player joins and leaves.
Player Detection: Logs are monitored for player join (is using new name) and leave events.
Message Formatting: $$user in messages is replaced with the actual player name.
Debugging: Added echo statements to print player names and generated messages.
Log Timestamps: Added a timestamp to each log line using echo "$(date '+%Y-%m-%d %H:%M:%S') - $LOGLINE" for better tracking.

### CODE REVIEW

**Comment by arguser** [comment]
Awesome work @ArrowPrint do we need an update on the Readme too?

**Comment by ArrowPrint** [comment]
Thanks a lot @arguser ,the following Parameters need to be set
_Customisable_
**Parameters**
DISCORD=1
DISCORD_HOOK=
DISCORD_MESSAGE_WELCOME=_Welcome hero_ **$$user**
DISCORD_MESSAGE_BYE=_Bye_ **$$user**
DISCORD_MESSAGE_STOP=**$$WORLD_NAME** _is shutting down_
DISCORD_MESSAGE_START=	_Brave hero, the world of_ **$$WORLD_NAME** _awaits you. Feel free to join_ **$$gameid**

Iam having trouble with the Discord bye message since there is no clear logline to show a player has logged off

**Comment by ArrowPrint** [comment]
should a i add to the Readme? should i convert to draft and do it?

**Comment by Micke90s** [comment]
> I am having trouble with the Discord bye message since there is no clear logline to show a player has logged off

You may could take a look on my earlier (unfinished)  test implementation: https://github.com/Micke90s/core-keeper-dedicated/blob/4e33fd8eadd56fb61743cced9c0a6f1f3bf22830/launch.sh#L22

I am not sure if it still works but I tried to match the `steamid` to a username by creating an environment variable which was just the steam id which contains the username.

**Comment by ArrowPrint** [comment]
@Micke90s I tried that initially,but doesn't work....that logline comes when connection times out before character selection...but not when you exit after selecting character for some reason

**Comment by Diyagi** [comment]
> @Micke90s I tried that initially,but doesn't work....that logline comes when connection times out before character selection...but not when you exit after selecting character for some reason

For me that line shows when disconnecting after character selection, i selected my character, walked around for a min then left.
image

**Comment by Diyagi** [comment]
> It seems that there are two handlers for `OnDisconnected` in the `Pug.Other.dll` ( `Pug.Platform.SteamNetworking` class) which will cause different messages.
> 
> ```cs
> public void OnDisconnected(ConnectionInfo info)
> {
>     Debug.Log("Client got disconnect from userid:" + info.Identity.SteamId.ToString() + " with reason:" + info.EndReason.ToString());
> ```
> 
> ```cs
> public void OnDisconnected(Connection connection, ConnectionInfo info)
> {
>     Debug.Log("Disconnected from userid:" + info.Identity.SteamId.ToString() + " with reason " + info.EndReason.ToString());
> ```
> 
> I am not sure how reliable this will be when the server supports Crossplay. (Does Crossplay already work?)

Could it be one for direct connect and other for steam relay ?

**Comment by arguser** [comment]
Hey @ArrowPrint are we good to go?

**Comment by arguser** [comment]
> should a i add to the Readme? should i convert to draft and do it?

No need to make it a draft, if you can add another commit with the changes on the README, thank you!

**Comment by Diyagi** [comment]
@arguser This can be closed btw, i cherry picked the commits from here into #62, and even if more things were to be added, its better off just making another pr anyway since this pr is in the 1.0 version.

**Pull request closed without merging**
