### PR TITLE
Refactor and improvements

### LINKED ISSUE #42: Unraid: Server isn't starting after downloading (FIX PROPOSED)
Any ideas what is going on? It should just deploy the container, download the files and make the necessary folders and logs etc. However it's not starting and not making any logs etc either. So I cannot even see what is going on.

Both the DIRs are just empty.

```
steamcmd.sh[8]: Restarting steamcmd by request...
tid(13) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
UpdateUI: skip show logotid(26) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.00 (0 / 73781292)
 Update state (0x61) downloading, progress: 92.89 (68538412 / 73781292)
Success! App '1007' fully installed.
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 10.84 (50712620 / 467785005)
 Update state (0x61) downloading, progress: 15.77 (73781292 / 467785005)
 Update state (0x61) downloading, progress: 69.11 (323268613 / 467785005)
 Update state (0x61) downloading, progress: 97.58 (456468989 / 467785005)
Success! App '1963720' fully installed.
tid(108) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
minidumps folder is set to /tmp/dumps
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1709846822
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1007' already up to date.
Success! App '1963720' already up to date.
xvinfo:  Unable to open display :99
Failed to start Xvfb, retry: 1
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
X-Video Extension version 2.2
screen #0
 no adaptors present
chmod: cannot access './CoreKeeperServer': No such file or directory
-batchmode -logfile CoreKeeperServerLog.txt -world 0 -worldname Babs World -worldseed 0 -worldmode 0 -gameid 1q2w3e4r5t6y7u8i9o0pzxc -maxplayers 10 -season -1
Started server process with pid 137
./launch.sh: line 72: ./CoreKeeperServer: No such file or directory

```

### LINKED ISSUE #53: Server crash - Segmentation faul
Hey starting today our server started crashing.

There isn't much in the log, only this.
``
./launch.sh: line 97:    86 Segmentation fault      (core dumped) DISPLAY=:99 LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../Steamworks SDK Redist/linux64/" ./CoreKeeperServer "${params[@]}"
``

[worlds.zip](https://github.com/user-attachments/files/16913590/worlds.zip)

If you need any more information, feel free to let me know.

### LINKED ISSUE #57: World data does not save to /home/steam/core-keeper-data by default
I'm not sure where it saves by default, but the `/home/steam/core-keeper-data` directory remained empty no matter what I specified in `docker-compose.yml` volumes.

It seems that if the `DATA_PATH` value in core.env is left empty, that parameter is not passed to the game launcher in `launch.sh`.  Once I set `DATA_PATH=/home/steam/core-keeper-data` in core.env, the world data finally saved to that path.

### PR DESCRIPTION
**Pull request by Diyagi**
- Added custom `PUID` and `PGID`
   - These ENVs default to 1000 and can be changed by setting both to other IDs
   - The container will always enforce these IDs upon initialization via `chown`
   - Should avoid issues when mounting save folders inside the container (figured the hard way that the server does not exit when it cannot write to the save file :c )
 - Fix X11 Sockets folder permissions
    - X11 Sockets folder should always be owned by root, and have its permission set to `777` (rwxrwxrwx)
 - Dockerfile Refactor
    - Moved `COPY` command to be executed after `apt-get` `RUN` command so docker can use build cache for test builds
    - Removed some dependencies that were being added via `apt-get` that seemed unnecessary **(More about this at the end)**
    - Added `tzdata`, this adds the possibility to change the container timezone by using the ENV `TZ=` ( Will come in handy with #60 )
 -  `entry.sh` Rewritten
    - This file was repurposed to handle the root part of the initialization like `usermod` `groupmod` `chown`
    - This will also check if the user is trying to run the image as root, in this case the container will exit.
    - Also checks for write permission to `STEAMAPPDIR` and `STEAMAPPDATADIR`
    - After everything that needs root is done it will proceed to execute the other scripts as `steam` user
 - `setup.sh` Is basically what the old `entry.sh` did but refactored, mostly to make it cleaner.
 - `launch.sh` Refactor
    - Removed a lot of code that seemed unnecessary **(More about this at the end)**
    - Moved Core Keeper Server arguments compilation/build to its own file
    - Added tail for the log file
    - Removed the `DISCORD` ENV, now it only checks if `DISCORD_HOOK` ENV is not empty to send the webhook push
    - Silenced `curl` output, it will still output in case of an error, but for success it will not output anything to `stdout`
 - `compile-parameters.sh` script now handles the argument compilation/build and should be ran with `source`
    - Logs files are now saved to the `logs` folder
    - Each server start should now generate its own file
    - Parameters are available in the array variable `params`
    - The path to the current log file is also available in the variable `logfile`
    - Modifying arguments now should be a lot easier and straight forward
 - Discord integration by @ArrowPrint
    
Now, i know some code that i removed from `launch.sh` and some dependencies i removed from `Dockerfile` were there to fix an issue with green obsidian wall around spawn, but after removing those i generated and tested 10+ different maps and never found any issue with those.
In my tests i lowered the outer wall and walked until i reached the end of the map and didn't find a single issue, as for hardware, i was using an GCP VM without an GPU.
It is possible that this issue got fixed in some patch, and if its the case simply merging this PR would not be a good idea.
Please let me know what you think.

Fixes #42, Fixes #57, Fixes #53

### CODE REVIEW

**Comment by Diyagi** [comment]
Theres more things i want to work on, i will convert this to a draft for now.

**Comment by Diyagi** [comment]
Should fix #42 and #57

**Comment by Renari** [comment]
Tried your branch and it fixed all the issues I was having trying to deploy on TrueNAS.

**Comment by Diyagi** [comment]
I made the choice of not printing the logs lines with timestamps because it seemed unnecessary, it is already possible to get logs from docker with timestamps by using `docker logs -t`.

**Comment by Diyagi** [comment]
Changed the build action to trigger on an new release in github.
Before merging this, i do recommend cherry-picking just the action build commits and creating an tag release of the current state of main branch as `1.0.0`, this will make sure that anyone wanting to run an older version of core keeper can do so by using an older version of the image where issues with world gen are fixed.
After that this branch can be merged and another tag release can be made.

**Comment by Micke90s** [comment]
I just saw that the new line `\n` in the `SEASON` description does not work as suspected. I think `<br/>` should work. Could you please check this?
https://github.com/Diyagi/core-keeper-dedicated/blob/e86e15d6c7dea18abf2c4bf6443fe3b3e6af758a/README.md?plain=1#L101

**Comment by Diyagi** [comment]
> I just saw that the new line `\n` in the `SEASON` description does not work as suspected. I think `<br/>` should work. Could you please check this? https://github.com/Diyagi/core-keeper-dedicated/blob/e86e15d6c7dea18abf2c4bf6443fe3b3e6af758a/README.md?plain=1#L101

Oh, thats true, sorry
I dont usually deal with readme, i throw it to a friend who likes to do this e.e

**Pull request merged**
