### PR TITLE
Add support for ARM64 architecture

### LINKED ISSUE #36: Failed to install app '1963720' (Requires 64bit operating system)
I have jumped through some hoops to get this docker container to even run on my Oracle ARM VM. But I eventually got Docker to work by using Qemu and adding `platform: linux/amd64` to the docker-compose.yml file.

However, now when I've got the Steamcmd to actually run inside the container, I get this error:
`Failed to install app '1963720' (Requires 64bit operating system)`

It seems like an obvious problem, but I'm not sure _why_ it occurs, considering that I explicitly named the platform to use linux/amd64, and even when exec:ing into the container, I get these results:
```
$ getconf LONG_BIT
64
$ uname -m
x86_64
```
Which should confirm that the container is actually running in 64-bit.

Just to be clear, no other changes have been made to the files except adding the platform specification in docker-compose. And yes it's the newest version of the image.

### PR DESCRIPTION
**Pull request by feserr**
Add support for ARM64 architectures using Box64.

This change is based on the https://github.com/thijsvanloef/palworld-server-docker which supports ARM64 using BOX64.

The AMD64 build stays intact. The only general changes are:

- Exposing the server port at the Docker Compose example file.
- Add Depot Downloaded as an alternative to `steamcmd` for machines not compatible with x86. It can be configured at the environmental variables.
- Force the download of the dedicated server to Linux and x64 architecture.

resolves #36 #45

### CODE REVIEW

**Comment by Micke90s** [comment]
As `ARM64_DEVICE` is an environment variable it should not be required to set it in the docker file or? It should work if the variable is set via `docker-compose` or `-e` on startup of the container. Or did I miss some point?

**Comment by feserr** [comment]
I have tested by removing it at the image, so it uses `generic` and the set it to `adlink` as my systems is an Oracle one. Everything is working so far. I will remove the variable from there and write in the README that it needs to be set there.

**Comment by Micke90s** [comment]
Just tried to build the amd64 docker file on my Linux host an on Windows (WSL). Unfortunately, there are two errors. The arm64 build works on raspberry. (I only can build but not test on the raspberry, as raspberry 4 seems to be too weak)

On Linux:
```docker build --platform=linux/amd64 -t escapingnetwork/core-keeper-dedicated .

Sending build context to Docker daemon  214.5kB
Step 1/27 : FROM cm2network/steamcmd:root AS base-amd64
 ---> 948fa5048611
Step 2/27 : FROM --platform=arm64 sonroyaalmerol/steamcmd-arm64:root-2024-11-24 AS base-arm64
 ---> bcf59c9d3c4a
Step 3/27 : ARG TARGETARCH
 ---> Using cache
 ---> 05c63c132527
Step 4/27 : FROM base-${TARGETARCH}
invalid reference format
```
I will need to check if this is cause by some host system problems. 🤔 

On Windows (WSL): 
```
 > [stage-2 4/8] RUN case "${TARGETARCH}" in         "amd64") DEPOT_DOWNLOADER_FILENAME=DepotDownloader-linux-x64.zip ;;         "arm64") DEPOT_DOWNLOADER_FILENAME=DepotDownloader-linux-arm64.zip ;;     esac     && wget --progress=dot:giga "https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.7.4/${DEPOT_DOWNLOADER_FILENAME}" -O DepotDownloader.zip     && unzip DepotDownloader.zip     && rm -rf DepotDownloader.xml     && chmod +x DepotDownloader     && mv DepotDownloader /usr/local/bin/DepotDownloader:
0.423 /bin/sh: 1: wget: not found
```
May wget is missing in the base image and must be installed.

**Comment by feserr** [comment]
I have added `wget` for the normal build as the image doesn't have it.

Also fix the error where `TARGETARCH` becomes empty after using the build image at line:

```
FROM base-${TARGETARCH}
```

I have tested it on an AMD64 machine and build it correctly.

**Comment by Micke90s** [comment]
> I have added `wget` for the normal build as the image doesn't have it.
> 
> Also fix the error where `TARGETARCH` becomes empty after using the build image at line:
> 
> ```
> FROM base-${TARGETARCH}
> ```
> 
> I have tested it on an AMD64 machine and build it correctly.

Thank you. 

The amd64 build works perfekt. Just tried build and run on my windows (WSL / Debian) host.
The arm64 build als works fine. (Im unable to run, but this is a problem of the raspberry 4)

**Comment by feserr** [comment]
> > I have added `wget` for the normal build as the image doesn't have it.
> > Also fix the error where `TARGETARCH` becomes empty after using the build image at line:
> > ```
> > FROM base-${TARGETARCH}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have tested it on an AMD64 machine and build it correctly.
> 
> Thank you.
> 
> The amd64 build works perfekt. Just tried build and run on my windows (WSL / Debian) host. The arm64 build als works fine. (Im unable to run, but this is a problem of the raspberry 4)
> 
> Edit: The build on my Debian host still throws `invalid reference format` I will try to set up a virtual machine later. But I think this is more a local problem.
> 
> Edit: I can verify the amd64 build and run on a fresh Debian installation (virtual machine)👍

The ARM64 image that is uses is only compatible with Raspberry Pi 5 as mention here: https://github.com/sonroyaalmerol/steamcmd-arm64?tab=readme-ov-file#box64-builds

You can create a Free forever Oracle ARM instance and use it there as I do.

**Comment by arguser** [comment]
Hello @feserr thank you for this PR. LGTM, are we good to go?

Thank you @Micke90s too, as always.

**Comment by feserr** [comment]
> Hello @feserr thank you for this PR. LGTM, are we good to go?
> 
> Thank you @Micke90s too, as always.

Sure, it requires a reviewer approval. Who should do it?

**Comment by Micke90s** [comment]
> The ARM64 image that is uses is only compatible with Raspberry Pi 5 as mention here: https://github.com/sonroyaalmerol/steamcmd-arm64?tab=readme-ov-file#box64-builds

@feserr Thank you. I missed that. Now I know why all my implementations failed 🤣 At least tests looked similar to your solution, so I wasn’t wrong completely. 😄 

> You can create a Free forever Oracle ARM instance and use it there as I do.
@feserr Thank you. Sounds very interesting. I will take a look on this. 

> Thank you @Micke90s too, as always.
@arguser You're welcome. 


I wish you a nice weekend 😄

**Pull request merged**
